# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python_digest.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13python_digest.proto\x12\x06\x44igest\"\x1f\n\x0eServiceRequest\x12\r\n\x05input\x18\x01 \x01(\t\"!\n\x0fServiceResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2M\n\x06\x44igest\x12\x43\n\x0eRemoteFunction\x12\x16.Digest.ServiceRequest\x1a\x17.Digest.ServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_digest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREQUEST']._serialized_start=31
  _globals['_SERVICEREQUEST']._serialized_end=62
  _globals['_SERVICERESPONSE']._serialized_start=64
  _globals['_SERVICERESPONSE']._serialized_end=97
  _globals['_DIGEST']._serialized_start=99
  _globals['_DIGEST']._serialized_end=176
# @@protoc_insertion_point(module_scope)
