# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmyservice\"\x1f\n\x0eServiceRequest\x12\r\n\x05input\x18\x01 \x01(\t\"!\n\x0fServiceResponse\x12\x0e\n\x06output\x18\x01 \x01(\t2V\n\tMyService\x12I\n\x0eRemoteFunction\x12\x19.myservice.ServiceRequest\x1a\x1a.myservice.ServiceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVICEREQUEST']._serialized_start=28
  _globals['_SERVICEREQUEST']._serialized_end=59
  _globals['_SERVICERESPONSE']._serialized_start=61
  _globals['_SERVICERESPONSE']._serialized_end=94
  _globals['_MYSERVICE']._serialized_start=96
  _globals['_MYSERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
